### ISSUE TITLE
缺少软件包

### ISSUE THREAD

**Issue by jisuanjiQAQ** [XayahSuSuSu/Action-SGSI-build#28]
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package adoptopenjdk-11-hotspot
Error: Process completed with exit code 100.

**Comment by XayahSuSuSu** [comment]
https://github.com/XayahSuSuSu/Action-SGSI-build/commit/03f45b7efe9426ecf30a16266c7feade71dddc34
已修复
